# Entrace Example for AI Builders

จุดมุ่งหมายคือการทดสอบความรู้ปรับพื้นฐานสำหรับ AI Builders ทุกคำตอบสามารถหาได้จาก notebook ปรับพื้นฐาน `ai_builder_intro_python.ipynb`, `ai_builder_numpy.ipynb` และ `ai_builder_pandas.ipynb` 

เราหวังให้คุณพยามสุดความสามารถที่จะตอบ แต่ไม่จำเป็นต้องตอบได้ครบทุกข้อเพื่อที่จะได้รับการคัดเลือกเข้าโครงการ

## Python

1. หาก `a=1` และ `b=2.5` แล้ว, `c` = $0.5(a+2b^5)$, `c` มีค่าเท่าไหร่? $b^x$ เขียนใน Python ได้แบบนี้ `b**x`

In [1]:
a = 1
b = 2.5
#ans
c = 0.5 * (a + 2 * b ** 5)
c

98.15625

2. `a`, `b`, และ `c` เป็นตัวแปรชนิดอะไรบ้าง? (ลองใช้ `type(a)`)

In [2]:
a = 1
b = 2.5
c = 0.5 * (a + 2 * b ** 5)
#ans
print(type(a))
print(type(b))
print(type(c))
#int, float, float

<class 'int'>
<class 'float'>
<class 'float'>


3. จากตัวแปร `s = 'AI Builders - A Program For Kids Who Wants to AI Good Good'`, เราจะดึงคำว่า `AI Good` ออกมาได้อย่างไร?

In [3]:
s = 'AI Builders - A Program For Kids Who Wants to AI Good Good'
#ans
s[-12:-5]

'AI Good'

4. ใช้ loop `print` ทุก element ใน `l` ยกเว้น element ที่เขียนว่า `AI`

`l = ['AI','Builders','-','A','Program','For','Kids','Who','Wants','to','AI','Good','Good']`

ลองใช้ `for` และ `if` เพื่อกรอง element ที่มีค่าเป็น `AI` ออก

In [4]:
l = ['AI','Builders','-','A','Program','For','Kids','Who','Wants','to','AI','Good','Good']
#ans
for i in l:
    if(i != 'AI'):
        print(i)

Builders
-
A
Program
For
Kids
Who
Wants
to
Good
Good


5. เขียนฟังชั่น `midpoint` ที่หาจุดกึ่งกลางระหว่างตัวเลข `a` และ `b` 

In [5]:
def midpoint(a, b):
    #ans
    return (a + b) / 2

print(midpoint(1, 4))  # expected 2.5
print(midpoint(3, 3))  # expected 3
print(midpoint(-2, 2))  # expected 0

2.5
3.0
0.0


6. เขียนฟังชั่น `fizzbuzz` ที่รับตัวเลข `x`


- ถ้า `x` หารด้วย 2 ลงให้คืน string ว่า `fizz`
- ถ้า `x` หารด้วย 3 ลงให้คืน string ว่า `buzz`
- ถ้า `x` หารด้วยทั้ง 2 และ 3 ลงให้คืน string ว่า `fizzbuzz`
- นอกนั้นให้คืน `None`

ลองใช้ `if`, `elif` และ `else` ในฟังชั่น `fizzbuzz`

In [6]:
def fizzbuzz(x):
    #ans
    if(x % 2 == 0 and x % 3 == 0):
        return 'fizzbuzz'
    if(x % 2 == 0):
        return 'fizz'
    if(x % 3 == 0):
        return 'buzz'
for i in range(20):
    print(i,fizzbuzz(i))

0 fizzbuzz
1 None
2 fizz
3 buzz
4 fizz
5 None
6 fizzbuzz
7 None
8 fizz
9 buzz
10 fizz
11 None
12 fizzbuzz
13 None
14 fizz
15 buzz
16 fizz
17 None
18 fizzbuzz
19 None


## Numpy and Linear Algebra

In [ ]:
import numpy as np

1. สร้าง numpy array `a` ที่มีมิติ `3*3` โดยมีค่าเป็นตัวเลขจาก 1 ถึง 9 (ลองใช้ `np.arange` และ `np.reshape`)

In [7]:
import numpy as np
a = np.arange(1, 10)
a = a.reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. สร้าง numpy array `b` ที่มีมิติ `4*3` โดยมีค่าเป็นตัวเลขจาก 1 ถึง 12 (ลองใช้ `np.arange` และ `np.reshape`)

In [8]:
import numpy as np
b = np.arange(1, 13)
b = b.reshape(4, 3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

3. เราสามารถหาค่า `a` dot product `b` ได้หรือไม่-เพราะอะไร (ลองใช้ `a.dot(b)` หรือ `a@b`)

In [9]:
a = np.arange(1, 10)
a = a.reshape(3, 3)

b = np.arange(1, 13)
b = b.reshape(4, 3)
#ans
a@b
#ไม่ได้ เพราะ จำนวนหลักของ a (3) ไม่เท่ากับจำนวนแถวของ b (4)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

4. หาค่า `a` dot product (`b` transposed) (tranpose `b` ได้ด้วยคำสั่ง `b.T`)

In [10]:
a = np.arange(1, 10)
a = a.reshape(3, 3)

b = np.arange(1, 13)
b = b.reshape(4, 3)
#ans
a@b.T

array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266]])

5. มิติ (แถวและคอลัมน์) ของ `a` และ `b` คืออะไร (ลองใช้ `a.shape`)

In [11]:
a = np.arange(1, 10)
a = a.reshape(3, 3)

b = np.arange(1, 13)
b = b.reshape(4, 3)
#ans
a.shape, b.shape

((3, 3), (4, 3))

6. คูณทุก element ของ `a` ด้วย -1

In [12]:
a = np.arange(1, 10)
a = a.reshape(3, 3)
#ans
a *= -1
a

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

7. เปลี่ยนมิติของ `b` ให้เป็น `2*2*3` (ลองใช้ `np.reshape`)

In [13]:
b = np.arange(1, 13)
b = b.reshape(4, 3)
#ans
b = b.reshape(2, 2, 3)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

8. ค่าเฉลี่ยของแต่ละแถวของ `a` (`3*3`) คืออะไร (ลองใช้ `np.mean` สังเกตว่าควรใช้ `axis=1` หรือ `axis=0`)

In [14]:
import numpy as np

a = np.arange(1, 10)
a = a.reshape(3, 3)
#ans
np.mean(a, axis = 1)


array([2., 5., 8.])

9. ค่าเฉลี่ยของแต่ละคอลัมน์ของ `a` (`3*3`) คืออะไร (ลองใช้ `np.mean` สังเกตว่าควรใช้ `axis=1` หรือ `axis=0`)

In [15]:
import numpy as np

a = np.arange(1, 10)
a = a.reshape(3, 3)
#ans
np.mean(a, axis = 0)

array([4., 5., 6.])

10. ถ้าเราต้องการหา `[[1,2],[4,5]]` จาก `a` เราต้องเลือกอย่างไร

In [16]:
#เราสามารถ slice แต่ละส่วนของ `np.array` ได้เหมือนกับ list เช่น 
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [17]:
import numpy as np

a = np.arange(1, 10)
a = a.reshape(3, 3)
#ans
a[:2, :2]

array([[1, 2],
       [4, 5]])

## Pandas and Data Exploration

ดาวน์โหลดชุดข้อมูล [อุบัติเหตุบนโครงข่ายถนนของกระทรวงคมนาคม 2562](https://data.go.th/dataset/roadaccident) (ไฟล์ชื่อ `ubatiehtuthaangthnn.xlsx`) จาก [data.go.th](https://data.go.th/). ตอบคำถามต่อไปนี้

In [ ]:
import pandas as pd

1. อ่านไฟล์ `ubatiehtuthaangthnn.xlsx` เข้ามาเป็น `pandas.DataFrame`; `df` มีกี่แถว-คอลัมน์? (ลองใช้ `df.shape`)

In [18]:
import pandas as pd
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)
#ans
df.shape
#19965 แถว 20 หลัก

(19965, 20)

2. เรียกดู 20 แถวแรกและ 20 แถวสุดท้ายของ `df` (ลองใช้ `df.head(20)` และ `df.tail(20)`)

In [19]:
import pandas as pd
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)
#ans
print(df.head(20))
print(df.tail(20))

   01/01/2019  00:20   02/01/2019         05:12   
4            2019     01/01/2019  00:25   01/01/2019         09:54   
5            2019     01/01/2019  00:30   01/01/2019         11:22   
6            2019     01/01/2019  00:30   03/01/2019         11:16   
7            2019     01/01/2019  00:35   01/01/2019         09:04   
8            2019     01/01/2019  00:40   01/01/2019         03:59   
9            2019     01/01/2019  00:45   01/01/2019         09:57   
10           2019     01/01/2019  00:45   01/01/2019         12:16   
11           2019     01/01/2019  00:45   02/01/2019         02:51   
12           2019     01/01/2019  01:00   01/01/2019         23:25   
13           2019     01/01/2019  01:00   02/01/2019         03:42   
14           2019     01/01/2019  01:00   02/01/2019         14:00   
15           2019     01/01/2019  01:04   01/01/2019         09:51   
16           2019     01/01/2019  01:15   02/01/2019         05:52   
17           2019     01/01/2019  01:20

3. จังหวัดใดมีอุบัติเหตุเยอะที่สุดถ้าอ้างอิงจาก `df`? (ลองใช้ `df['จังหวัด'].value_counts()`)

In [55]:
import pandas as pd
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)
#ans
df['จังหวัด'].value_counts()
#กรุงเทพมหานคร

กรุงเทพมหานคร    1844
ชลบุรี            938
นครราชสีมา        877
สุพรรณบุรี        727
สมุทรปราการ       649
                 ... 
ยะลา               72
พังงา              72
ชัยภูมิ            70
อำนาจเจริญ         51
ระนอง              35
Name: จังหวัด, Length: 77, dtype: int64

4. เลือกเฉพาะแถวที่เป็นอุบัติเหตุที่มีผู้เสียชีวิต 0 ราย / มีอุบัติเหตุที่ไม่มีผู้เสียชีวิตกี่ครั้ง? (เราสามารถกรอง dataframe ได้ด้วยคำสั่ง `df[df['จำนวนผู้เสียชีวิต']==0]`)

In [57]:
import pandas as pd
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)
#ans
df[df['จำนวนผู้เสียชวิต']==0]
#17296 ครั้ง (จำนวนแถว)


ปีที่เกิดเหตุ วันที่เกิดเหตุ   เวลา  ... สภาพอากาศ   LATITUDE   LONGITUDE
0               2019     01/01/2019  00:00  ...    แจ่มใส  14.959105  100.873463
1               2019     01/01/2019  00:03  ...    แจ่มใส  15.210738  104.862689
3               2019     01/01/2019  00:20  ...    แจ่มใส  18.601721   98.804204
4               2019     01/01/2019  00:25  ...    แจ่มใส  15.866389  100.590010
5               2019     01/01/2019  00:30  ...    แจ่มใส   9.949354   99.063479
...              ...            ...    ...  ...       ...        ...         ...
19955           2019     31/12/2019  23:00  ...    แจ่มใส  13.165411   99.842039
19956           2019     31/12/2019  23:10  ...    แจ่มใส   8.812859   99.166543
19957           2019     31/12/2019  23:20  ...    แจ่มใส  12.951183  100.958457
19958           2019     31/12/2019  23:20  ...    แจ่มใส  18.589153   99.042735
19961           2019     31/12/2019  23:35  ...    แจ่มใส   8.092608   98.811692

[17296 rows x 20 columns]


5. ค่าเฉลี่ยของ latitude, logitude ของอุบัติเหตุที่เกิดขึ้นในจังหวัดเชียงใหม่อยู่ที่เท่าใด? (กรองให้เหลือแค่จังหวัดเชียงใหม่แล้วหาค่าเฉลี่ยด้วยคำสั่ง `df.LATITUDE.mean()` และ `df.LONGITUDE.mean()`)

In [58]:
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)
#ans
ar = df[df['จังหวัด'] == 'เชียงใหม่']
ar.LATITUDE.mean(), ar.LONGITUDE.mean()

(18.91090138416936, 98.91462670826341)

6. `ลักษณะการเกิดอุบัติเหตุ ` แบบใดมี `จำนวนผู้เสียชวิต` โดยเฉลี่ยสูงที่สุด?

In [65]:
import pandas as pd
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)
#ans
ar = df.groupby(['ลักษณะการเกิดอุบัติเหตุ '])['จำนวนผู้เสียชวิต'].mean().reset_index()
ar.sort_values(by='จำนวนผู้เสียชวิต', ascending=False)
#ชนรถไฟ

ลักษณะการเกิดอุบัติเหตุ   จำนวนผู้เสียชวิต
8                                     ชนรถไฟ          6.000000
2                                   ชนขณะแซง          0.794118
25                      รถยนต์พลิกคว่ำ ตกถนน          0.750000
18    รถจักรยานยนต์ชนรถจักรยานพลิกคว่ำ ตกถนน          0.750000
12       ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง)          0.615385
4                               ชนคนเดินเท้า          0.610714
0                      ชนกัน/ชนยานพาหนะอื่นๆ          0.437209
7                                    ชนรถจอด          0.436548
13                                   ตกจากรถ          0.428571
17                         รถจักรยานยนต์ชนคน          0.400000
11                     ชนเป็นมุมบริเวณทางแยก          0.385135
21            รถยนต์ชนรถจักรยานยนต์/รถสามล้อ          0.250000
1                          ชนกันหรือเฉี่ยวชน          0.232843
23                     รถยนต์ชนวัตถุ สิ่งของ          0.172414
9                              ชนสิ่งกีดขวาง          0.161616
28                              เลี้ยว/ถอยชน          0.157895
6                                     ชนท้าย          0.154588
27                                  เฉี่ยวชน          0.152490
22                              รถยนต์ชนรถไฟ          0.148148
16      รถจักรยานยนต์ชนกับรถจักรยาน รถสามล้อ          0.142857
3                                   ชนขอบทาง          0.128889
26                                    อื่น ๆ          0.128205
15                             พลิกคว่ำตกถนน          0.106300
29           เสียหลัก ไปอยู่ในช่องจราจรอื่นๆ          0.080128
5   ชนตู้เก็บเงิน ไม้กั้นเลน อุปกรณ์เก็บเงิน          0.052632
10                           ชนอุปกรณ์งานทาง          0.047334
24           รถยนต์ชนสัตว์ รถลากจูงด้วยสัตว์          0.035714
20                               รถยนต์ชนกัน          0.000000
19                     รถจักรยานยนต์ชนรถยนต์          0.000000
14                                  พลิกคว่ำ          0.000000

7. อุบัติเหตุที่เกิดจาก `มูลเหตุสันนิษฐาน` เป็น `ขับรถเร็วเกินกำหนด` มีโอกาสทำให้มีผู้เสียชีวิตมากกว่า `มูลเหตุสันนิษฐาน` อื่นหรือไม่?

In [66]:
import pandas as pd
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)
#ans
df['drive_fast_flag'] = df['มูลเหตุสันนิษฐาน'].map(lambda x: 1 if x == 'ขับรถเร็วเกินกำหนด' else 0)
df['has_death'] = df['จำนวนผู้เสียชวิต'].map(lambda x: 1 if x >= 1 else 0)
df.groupby('drive_fast_flag').has_death.mean()
#ไม่

drive_fast_flag
0    0.157192
1    0.124128
Name: has_death, dtype: float64